openapi: 3.0.1
info:
  title: Ronscript Plugin
  description: A plugin that allows the user to create, retrieve, and manage scripts using ChatGPT.
  version: 'v1'
servers:
  - url: http://localhost:5003
paths:
  /upload:
    post:
      operationId: uploadFiles
      summary: Upload files from the UPLOAD folder to the scripts list
      responses:
        "200":
          description: OK
  /scripts:
    post:
      operationId: addScript
      summary: Add a script to the list
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/addScriptRequest'
      responses:
        "200":
          description: OK
    get:
      operationId: getScripts
      summary: Get the list of scripts
      responses:
        "200":
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/getScriptsResponse'
    delete:
      operationId: deleteScript
      summary: Delete a script from the list
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/deleteScriptRequest'
      responses:
        "200":
          description: OK

components:
  schemas:
    addScriptRequest:
      type: object
      required:
      - script
      properties:
        script:
          type: string
          description: The script to add to the list.
          required: true
    getScriptsResponse:
      type: object
      properties:
        scripts:
          type: array
          items:
            type: string
          description: The list of scripts.
    deleteScriptRequest:
      type: object
      required:
      - script_idx
      properties:
        script_idx:
          type: sting
          description: The name of the script to delete.
          required: true
